version: '3.8'

services:
  rasa:
    build: ./  # Assuming Dockerfile is in the root of `app/`
    ports:
      - "5050:5050"  # Mapping container port to host port
    volumes:
      - ./rasa:/app/rasa
    command: >
      /app/venv/bin/rasa run --model /app/rasa/models --enable-api --cors "*" --port 5050

  action_server:
    build: ./actions
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    command: >
      /app/venv/bin/rasa run actions
