version: '3.8'

services:
  rasa:
    build: .
    container_name: rasa_bot
    ports:
      - "5005:5005"
    volumes:
      - ./rasa:/app/rasa
    command: rasa run --enable-api --cors "*" --port 5005
